# Generated by Django 3.1.1 on 2020-09-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibba_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='short_description',
            field=models.TextField(default="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. "),
            preserve_default=False,
        ),
    ]
