# Generated by Django 3.1.1 on 2020-10-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibba_app', '0004_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=95),
        ),
        migrations.AlterField(
            model_name='registration',
            name='message',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
