# Generated by Django 3.1.1 on 2020-10-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibba_app', '0006_auto_20201004_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='address',
            field=models.CharField(default='hfghfghfg', max_length=95),
            preserve_default=False,
        ),
    ]
