# Generated by Django 3.1.1 on 2020-10-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibba_app', '0007_trainer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_at_home',
            new_name='is_new',
        ),
    ]
