# Generated by Django 3.1.1 on 2020-10-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibba_app', '0009_auto_20201007_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='parent_module',
            new_name='type',
        ),
    ]
